[package]
name = "progs"
version = "0.1.0"
edition = "2021"
authors = ["Terrydaktal <9lewis9@gmail.com>"]
description = "Ultra-fast System Programs Manager written in Rust with egui"

[dependencies]
eframe = "0.28"
egui = "0.28"
regex = "1.10"
open = "5.1"
arboard = "3.4"
chrono = "0.4"
nucleo-matcher = "0.3.1"
